<a href="https://colab.research.google.com/github/lukaszplust/data-science-learn/blob/main/supervised/03_classification/07_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <a name='0'></a> Import bibliotek

In [2]:
import numpy as np
import pandas as pd
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)
sklearn.__version__

'1.2.2'

### <a name='1'></a> Wygenerowanie danych

In [3]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie',
          'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie',
               'umiarkowanie', 'ciepło', 'zimno']

spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']      

raw_df = pd.DataFrame(data={'pogoda': pogoda, 'temperatura': temperatura, 'spacer': spacer})
df = raw_df.copy()
df

       pogoda   temperatura spacer
0  słonecznie        ciepło    tak
1   deszczowo         zimno    nie
2   pochmurno        ciepło    tak
3   deszczowo        ciepło    nie
4  słonecznie        ciepło    tak
5  słonecznie  umiarkowanie    tak
6   pochmurno  umiarkowanie    nie
7   pochmurno        ciepło    tak
8  słonecznie         zimno    nie

### <a name='2'></a> Przygotowanie danych do modelu

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['spacer']= encoder.fit_transform(spacer)#na encoder wywołuje fit_transform(nazwa zmiennej)
df

       pogoda   temperatura  spacer
0  słonecznie        ciepło       1
1   deszczowo         zimno       0
2   pochmurno        ciepło       1
3   deszczowo        ciepło       0
4  słonecznie        ciepło       1
5  słonecznie  umiarkowanie       1
6   pochmurno  umiarkowanie       0
7   pochmurno        ciepło       1
8  słonecznie         zimno       0

In [5]:
df = pd.get_dummies(df, columns=['pogoda', 'temperatura'], drop_first=True)#get_dummies przypasowuje do wyszukiwanych(pogoda,temperatura) 0 oraz 1. Jesli dla pogoda_pochmurno jest pochmurno to 1, else 0 itd.
df

,spacer,pogoda_pochmurno,pogoda_słonecznie,temperatura_umiarkowanie,temperatura_zimno
0,1,0,1,0,0
1,0,0,0,0,1
2,1,1,0,0,0
3,0,0,0,0,0
4,1,0,1,0,0
5,1,0,1,1,0
6,0,1,0,1,0
7,1,1,0,0,0
8,0,0,1,0,1

In [6]:
data = df.copy()
target = data.pop('spacer')

data

,pogoda_pochmurno,pogoda_słonecznie,temperatura_umiarkowanie,temperatura_zimno
0,0,1,0,0
1,0,0,0,1
2,1,0,0,0
3,0,0,0,0
4,0,1,0,0
5,0,1,1,0
6,1,0,1,0
7,1,0,0,0
8,0,1,0,1

In [9]:
target#targetem sa 0 i 1 dla zmiennej spacer

0    1
1    0
2    1
3    0
4    1
5    1
6    0
7    1
8    0
Name: spacer, dtype: int64

In [11]:
data

   pogoda_słonecznie  temperatura_umiarkowanie  temperatura_zimno
0                  1                         0                  0
1                  0                         0                  1
2                  0                         0                  0
3                  0                         0                  0
4                  1                         0                  0
5                  1                         1                  0
6                  0                         1                  0
7                  0                         0                  0
8                  1                         0                  1

### <a name='3'></a> Klasyfikator bayesowski

In [10]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(data, target)

GaussianNB()

In [12]:
model.score(data, target)

0.7777777777777778

In [14]:
data.iloc[[0]]#predykcja na 1 wierszu jest to slonecznie i cieplo

   pogoda_słonecznie  temperatura_umiarkowanie  temperatura_zimno
0                  1                         0                  0

In [16]:
model.predict(data.iloc[[0]])#wynikiem jest tablica np.array o wartosci 1

array([1])

In [17]:
encoder.classes_

array(['nie', 'tak'], dtype='<U3')

In [18]:
encoder.classes_[model.predict(data.iloc[[0]])[0]]

'tak'

In [ ]:
model.predict_proba(data.iloc[[0]])

array([[0.000006, 0.999994]])